LayoutAndViewsAssignment2/Controllers/FeverCheckController.cs
using LayoutAndViewsAssignment2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LayoutAndViewsAssignment2.Controllers
{
    public class FeverCheckController : Controller
    {
        // GET: FeverCheck
        public ActionResult Index()
        {
            return View();
        }

        // GET: FeverCheck/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: FeverCheck/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FeverCheck/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult CalculateTemperatureResult()
        {
            if (Request["txtTemperature"].ToString() == "")
            {
                return View("Index");
            }
            decimal temperatureAmount;
            try
            {
                temperatureAmount = Convert.ToDecimal(Request["txtTemperature"].ToString());
            }
            catch
            {
                ViewBag.Message = ("Please enter an acceptable number");
                return View("Index");
            }
            ViewBag.Message = FeverCheckModels.tempChecker(temperatureAmount);
            return View("Index");
        }
    }
}

LayoutAndViewsAssignment2/Controllers/GuessingGameController.cs
using LayoutAndViewsAssignment2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LayoutAndViewsAssignment2.Controllers
{
    public class GuessingGameController : Controller
    {
        int guesses = 0;
        // GET: GuessingGame
        public ActionResult Index()
        {
            Session.Clear();
            Session["RandomNumber"] = GuessingGameModels.RandomNumberGenerator();
            ViewBag.Message = "";
            return View();
        }

        [HttpPost]
        public ActionResult CheckGuess()
        {
            string outputMessage;
            try
            {
                outputMessage = GuessingGameModels.CheckGuess(Convert.ToInt32(Request["txtGuess"]), Convert.ToInt32(Session["RandomNumber"].ToString()));
            }
            catch
            {
                ViewBag.Message = "Please try again";
                return View("Index");
            }
            Session["Guesses"] = guesses;
            ViewBag.Message = outputMessage;
            return View("Index");
        }
    }
}

LayoutAndViewsAssignment2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - APS.NET Assignment</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ASP.NET Assignment", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Projects", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Fever Check", "Index", "FeverCheck")</li>
                    <li>@Html.ActionLink("Guessing Game", "Index", "GuessingGame")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.ToString("yy-MM-dd") - Dennis Klint</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>